# Configuration for Travis CI
language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
branches:
  only:
    - master
script:
  mvn -Dsurefire.useFile=false test site
sudo: false
cache:
  directories:
    - $HOME/.m2
# End .travis.yml
