# Configuration for Travis CI
language: java
matrix:
  fast_finish: true
  include:
    - env: IMAGE=maven:3-openjdk-16 JDOC=Y GUAVA=30.1.1-jre
    - env: IMAGE=maven:3-jdk-11
    - env: IMAGE=maven:3-jdk-10 SITE=Y
    - env: IMAGE=maven:3-jdk-8 JDOC=Y
branches:
  only:
    - main
    - scratch
env:
  global:
  - DOCKERRUN="docker run -it --rm -v $PWD:/src -v $HOME/.m2:/root/.m2 -w /src"
services:
  - docker
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull $IMAGE
script:
  - export FLAGS="-Dcheckstyle.skip -Dsurefire.useFile=false -Dsurefire.threadCount=1 -Dsurefire.perCoreThreadCount=false -Djavax.net.ssl.trustStorePassword=changeit"
  - if [ "$GUAVA" ]; then export FLAGS="$FLAGS -Dguava.version=$GUAVA"; fi
  - if [ $JDOC = "Y" ]; then export JDOC=javadoc:javadoc; fi
  - if [ $SITE = "Y" ]; then export SITE="site"; fi
  - $DOCKERRUN $IMAGE mvn $FLAGS test $JDOC $SITE
cache:
  directories:
    - $HOME/.m2
git:
  depth: 1000
# End .travis.yml
